name: Crea y publica Docker V

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Construye Imagen Docker
    runs-on: ubuntu-latest

    steps:
      - name: Clona Repositorio
        uses: actions/checkout@v2
      - name: Login a DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Comando construir Imagen
        run: docker build -t yourusername/yourimagename:latest .
      - name: Comando publicar imagen
        run: docker push yourusername/yourimagename:latest

